POST http://127.0.0.1:8000/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin1234"
}

###
POST http://127.0.0.1:8000/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTc3OTM3MywiaWF0IjoxNzc5NjkyOTczLCJqdGkiOiJmNDJkY2QwZjkxMjc0ZGQ1YmI0MWUyMmY0NmQxN2I1MyIsInVzZXJfaWQiOiIxIn0.aFAHhvwwFWLCYj_IQN_JGEQafdnBXGfitsFzyCpoZtc"
}
###
GET http://127.0.0.1:8000/blog/posts/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5NjkzMjA1LCJpYXQiOjE3Nzk2OTI5MDUsImp0aSI6IjYzNWIyNGRjNGY4ZDRkZjJiOTg4ZWRhMTgxNTVhNDFhIiwidXNlcl9pZCI6IjIifQ.uTu0uQKLw2YTMZPh9PAHfK5DQczD8WPU5XAPpLI6R3w

###
POST http://127.0.0.1:8000/blog/posts/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5NjkzMjczLCJpYXQiOjE3Nzk2OTI5NzMsImp0aSI6IjQ0NWYwMDAwNGY0NTQzY2RiNjhkOTZjOTNkNDRlNGZiIiwidXNlcl9pZCI6IjEifQ.y4gMs_OtjjwyYRHhe8NbUi7cdYQXk80Qb6bCkO661Yc

{
    "title": "New Post",
    "description": "This is a description of the new post.",
    "content": "This is a new post created via API."
}